name: Build and Release PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex  # Ou texlive-latex-base se preferir pdflatex

    - name: Build PDF
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
      working-directory: ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: |
          main.pdf
        tag_name: v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
